# Generated by Django 5.2 on 2025-07-23 22:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceBaby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_baby', models.CharField(max_length=200, null=True)),
                ('advice_baby_en', models.CharField(max_length=200, null=True)),
                ('advice_baby_ar', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdviceBad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_bad', models.CharField(max_length=200, null=True)),
                ('advice_bad_en', models.CharField(max_length=200, null=True)),
                ('advice_bad_ar', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdviceBottel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_baby', models.CharField(max_length=200, null=True)),
                ('advice_baby_en', models.CharField(max_length=200, null=True)),
                ('advice_baby_ar', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdviceMoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_baby', models.CharField(max_length=200, null=True)),
                ('advice_baby_en', models.CharField(max_length=200, null=True)),
                ('advice_baby_ar', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdviceMother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_mather', models.CharField(max_length=200, null=True)),
                ('advice_mather_en', models.CharField(max_length=200, null=True)),
                ('advice_mather_ar', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HowTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('mother', 'Mother'), ('baby', 'Baby'), ('bad', 'Bad'), ('bottle', 'Bottle'), ('moon', 'Moon')], max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('content_en', models.TextField(blank=True, null=True)),
                ('content_ar', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=190, null=True)),
                ('last_name', models.CharField(max_length=190, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='preChild2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby', models.CharField(max_length=190, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('birth_date', models.DateField()),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_children2', to='pages.mother')),
            ],
        ),
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='pages.prechild2')),
            ],
        ),
        migrations.CreateModel(
            name='ChildPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='child_photos/')),
                ('pre', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='pages.prechild2')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedings', models.FloatField(default=0.0)),
                ('sleeping', models.FloatField(default=0.0)),
                ('Diapers', models.FloatField(default=0.0)),
                ('mother', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.mother')),
                ('pre', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.prechild2')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pages.prechild2')),
            ],
        ),
    ]
