# Generated by Django 4.1.13 on 2025-03-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='birth_date',
            new_name='day',
        ),
        migrations.AddField(
            model_name='child',
            name='month',
            field=models.DateTimeField(max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='year',
            field=models.DateTimeField(max_length=190, null=True),
        ),
    ]
