# Generated by Django 5.2 on 2025-04-21 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mother',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='password',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='child',
            name='photo',
            field=models.ImageField(blank=True, default='super.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mother',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='child',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.mother'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='first_name',
            field=models.CharField(max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='mother',
            name='last_name',
            field=models.CharField(max_length=190, null=True),
        ),
    ]
