# Generated by Django 5.2 on 2025-05-05 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='child',
        ),
    ]
