# Generated by Django 5.2 on 2025-04-21 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_mother_groups_remove_mother_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mother',
            name='user',
        ),
    ]
