# Generated by Django 5.2 on 2025-05-05 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_task_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pages.child'),
        ),
    ]
