# Generated by Django 5.1.7 on 2025-03-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_child_mother_alter_mother_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceMoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_moon', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BabyBottleAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby_bottle_advice', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='advice_mother',
            old_name='advice_mather',
            new_name='advice_mother',
        ),
    ]
