# Generated by Django 5.2 on 2025-05-11 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_task_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='child',
            name='type',
        ),
        migrations.CreateModel(
            name='preChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('birth_date', models.DateField()),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_children', to='pages.mother')),
            ],
        ),
    ]
