# Generated by Django 5.1.7 on 2025-04-03 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_advicemoon_babybottleadvice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='day',
        ),
        migrations.RemoveField(
            model_name='child',
            name='month',
        ),
        migrations.RemoveField(
            model_name='child',
            name='year',
        ),
        migrations.AddField(
            model_name='child',
            name='date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='child',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth_rate', models.CharField(max_length=190, null=True)),
                ('date', models.DateField(default='2024-01-01')),
                ('height', models.FloatField(blank=True, help_text='Height in cm', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='pages.child')),
            ],
        ),
        migrations.CreateModel(
            name='HowTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('advice_baby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.advice_baby')),
                ('advice_moon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.advicemoon')),
                ('advice_mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.advice_mother')),
                ('baby_bottle_advice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.babybottleadvice')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2024-01-01')),
                ('content', models.TextField()),
                ('mother', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pages.mother')),
            ],
        ),
    ]
