# Generated by Django 5.1.7 on 2025-04-03 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_child_day_remove_child_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growthrecord',
            name='child',
        ),
        migrations.AlterField(
            model_name='growthrecord',
            name='growth_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='pages.child'),
        ),
    ]
