# Generated by Django 5.2 on 2025-05-11 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_child_birth_date_remove_child_type_prechild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pages.prechild'),
        ),
    ]
