# Generated by Django 5.2 on 2025-05-11 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_task_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pages.prechild'),
        ),
    ]
