# Generated by Django 5.1.7 on 2025-04-03 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_growthrecord_child_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='growthrecord',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='pages.child'),
        ),
        migrations.AlterField(
            model_name='growthrecord',
            name='growth_rate',
            field=models.CharField(max_length=190, null=True),
        ),
    ]
