# Generated by Django 5.1.7 on 2025-04-03 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_growthrecord_child_alter_growthrecord_growth_rate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
