# Generated by Django 5.1.7 on 2025-04-03 18:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_rename_tasks_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advice_bad',
            new_name='AdviceBaby',
        ),
        migrations.RenameModel(
            old_name='Advice_mother',
            new_name='AdviceBad',
        ),
        migrations.RenameModel(
            old_name='Advice_baby',
            new_name='AdviceMother',
        ),
        migrations.RenameField(
            model_name='advicebaby',
            old_name='advice_bad',
            new_name='advice_baby',
        ),
        migrations.RenameField(
            model_name='advicebad',
            old_name='advice_mother',
            new_name='advice_bad',
        ),
        migrations.RenameField(
            model_name='advicemother',
            old_name='advice_baby',
            new_name='advice_mother',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='Diapers',
            new_name='diapers',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='baby',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='child',
            name='date',
        ),
        migrations.RemoveField(
            model_name='child',
            name='type',
        ),
        migrations.AddField(
            model_name='child',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='growthrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mother',
            name='email',
            field=models.EmailField(max_length=190, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mother',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
