# Generated by Django 5.2 on 2025-05-12 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_task_child'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advicebottel',
            old_name='advice_baby',
            new_name='advice_bootel',
        ),
        migrations.RenameField(
            model_name='advicemoon',
            old_name='advice_baby',
            new_name='advice_moon',
        ),
    ]
