# Generated by Django 5.1.7 on 2025-04-03 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_rename_advice_bad_advicebaby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howto',
            name='advice_baby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.advicebaby'),
        ),
        migrations.AlterField(
            model_name='howto',
            name='advice_mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.advicemother'),
        ),
    ]
