# Generated by Django 5.2 on 2025-05-12 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_rename_advice_baby_advicebottel_advice_bootel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advicebottel',
            old_name='advice_bootel',
            new_name='advice_bottel',
        ),
    ]
