# Generated by Django 5.2 on 2025-05-12 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_rename_advice_bootel_advicebottel_advice_bottel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advicebottel',
            old_name='advice_bottel',
            new_name='advice_baby',
        ),
        migrations.RenameField(
            model_name='advicemoon',
            old_name='advice_moon',
            new_name='advice_baby',
        ),
    ]
