# Generated by Django 5.1.7 on 2025-04-04 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_howto_advice_baby_alter_howto_advice_mother'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='mother',
        ),
        migrations.AddField(
            model_name='task',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pages.child'),
        ),
    ]
