# Generated by Django 5.1.7 on 2025-04-13 04:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_remove_task_mother_task_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='howto',
            name='advice_moon',
        ),
        migrations.RemoveField(
            model_name='howto',
            name='baby_bottle_advice',
        ),
        migrations.RenameField(
            model_name='advicemother',
            old_name='advice_mother',
            new_name='advice_mather',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='diapers',
            new_name='Diapers',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='name',
            new_name='baby',
        ),
        migrations.RemoveField(
            model_name='child',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='child',
            name='mother',
        ),
        migrations.RemoveField(
            model_name='growthrecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='growthrecord',
            name='growth_rate',
        ),
        migrations.RemoveField(
            model_name='howto',
            name='advice_baby',
        ),
        migrations.RemoveField(
            model_name='howto',
            name='advice_mother',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.AddField(
            model_name='child',
            name='type',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='growthrecord',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='howto',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mother',
            name='password',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='child',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='child',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='growthrecord',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='pages.child'),
        ),
        migrations.AlterField(
            model_name='growthrecord',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='growthrecord',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='howto',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='mother',
            name='email',
            field=models.CharField(max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pages.child'),
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='AdviceMoon',
        ),
        migrations.DeleteModel(
            name='BabyBottleAdvice',
        ),
    ]
