# Generated by Django 5.2 on 2025-05-14 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_rename_advice_bottel_advicebottel_advice_baby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pages.prechild'),
        ),
    ]
