# Generated by Django 5.1.7 on 2025-04-13 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_howto_advice_moon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceBottel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_baby', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdviceMoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_baby', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='howto',
            name='advice_bad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='howto_bad', to='pages.advicebad'),
        ),
        migrations.AddField(
            model_name='howto',
            name='advice_bottle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='howto_bottle', to='pages.advicebaby'),
        ),
        migrations.AddField(
            model_name='howto',
            name='advice_moon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='howto_moon', to='pages.advicemother'),
        ),
        migrations.AddField(
            model_name='howto',
            name='advice_mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='howto_mother', to='pages.advicemother'),
        ),
    ]
