# Generated by Django 5.2 on 2025-04-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_remove_mother_password_child_mother_mother_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mother',
            name='children',
            field=models.ManyToManyField(related_name='mothers', to='pages.child'),
        ),
    ]
