# Generated by Django 5.2 on 2025-04-13 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_mother_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mother',
            name='children',
        ),
        migrations.AlterField(
            model_name='child',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.mother'),
        ),
    ]
