# Generated by Django 5.2 on 2025-05-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_rename_advice_mother_advicemother_advice_mather_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='howto',
            name='datetime',
        ),
    ]
