# Generated by Django 5.2 on 2025-05-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_remove_howto_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='howto',
            name='category',
            field=models.CharField(choices=[('mother', 'Mother'), ('baby', 'Baby'), ('bad', 'Bad'), ('bottle', 'Bottle'), ('moon', 'Moon')], default='mother', max_length=20),
            preserve_default=False,
        ),
    ]
