# Generated by Django 5.2 on 2025-05-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_howto_advice_baby_howto_advice_bad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='howto',
            name='advice_baby',
        ),
        migrations.RemoveField(
            model_name='howto',
            name='advice_bad',
        ),
        migrations.RemoveField(
            model_name='howto',
            name='advice_bottle',
        ),
        migrations.RemoveField(
            model_name='howto',
            name='advice_moon',
        ),
        migrations.RemoveField(
            model_name='howto',
            name='advice_mother',
        ),
    ]
