# Generated by Django 5.2 on 2025-06-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_remove_child_diapers_af_remove_child_diapers_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='diapers_status',
            field=models.CharField(choices=[('normal', 'Normal'), ('unnormal', 'Unnormal')], default='unnormal', max_length=20),
        ),
        migrations.AddField(
            model_name='child',
            name='feedings_status',
            field=models.CharField(choices=[('normal', 'Normal'), ('unnormal', 'Unnormal')], default='unnormal', max_length=20),
        ),
        migrations.AddField(
            model_name='child',
            name='sleeping_status',
            field=models.CharField(choices=[('normal', 'Normal'), ('unnormal', 'Unnormal')], default='unnormal', max_length=20),
        ),
    ]
