# Generated by Django 5.2 on 2025-06-22 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_child_diapers_status_child_feedings_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='diapers_status',
        ),
        migrations.RemoveField(
            model_name='child',
            name='feedings_status',
        ),
        migrations.RemoveField(
            model_name='child',
            name='sleeping_status',
        ),
    ]
