# Generated by Django 5.2 on 2025-06-23 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_remove_advicebaby_advice_baby_af_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='baby',
        ),
    ]
