# Generated by Django 5.2 on 2025-06-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_remove_child_baby'),
    ]

    operations = [
        migrations.AddField(
            model_name='prechild',
            name='baby',
            field=models.CharField(max_length=190, null=True),
        ),
    ]
