# Generated by Django 5.2 on 2025-06-23 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_prechild_baby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prechild',
            name='baby',
        ),
        migrations.CreateModel(
            name='preChild2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby', models.CharField(max_length=190, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('birth_date', models.DateField()),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_children2', to='pages.mother')),
            ],
        ),
    ]
