# Generated by Django 5.2 on 2025-06-26 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_remove_prechild_baby_prechild2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pages.prechild2'),
        ),
        migrations.AlterField(
            model_name='child',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='child_photos/'),
        ),
        migrations.DeleteModel(
            name='preChild',
        ),
    ]
