# Generated by Django 5.2 on 2025-06-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_alter_task_child_alter_child_photo_delete_prechild'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='vaccines',
            field=models.TextField(blank=True, null=True),
        ),
    ]
