# Generated by Django 5.2 on 2025-06-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_child_temp_child_vaccines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='vaccines',
        ),
    ]
