# Generated by Django 5.2 on 2025-06-26 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_remove_child_vaccines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='height',
        ),
        migrations.RemoveField(
            model_name='child',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='child',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='child',
            name='weight',
        ),
        migrations.CreateModel(
            name='ChildPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='child_photos/')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pages.child')),
            ],
        ),
    ]
