# Generated by Django 5.2 on 2025-06-26 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_remove_child_height_remove_child_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childphoto',
            name='child',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='pages.child'),
        ),
    ]
