# Generated by Django 5.2 on 2025-06-27 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_alter_childphoto_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childphoto',
            name='child',
        ),
        migrations.AddField(
            model_name='child',
            name='pre',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='pages.prechild2'),
        ),
        migrations.AddField(
            model_name='childphoto',
            name='pre',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='pages.prechild2'),
        ),
    ]
