# Generated by Django 5.2 on 2025-06-27 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_remove_childphoto_child_child_pre_childphoto_pre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='pre',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.prechild2'),
        ),
    ]
