# Generated by Django 5.2 on 2025-06-27 21:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_alter_child_pre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growthrecord',
            name='datetime',
        ),
        migrations.AddField(
            model_name='growthrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='growthrecord',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='growthrecord',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='pages.prechild2'),
        ),
        migrations.AlterField(
            model_name='growthrecord',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='growthrecord',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
