# Generated by Django 5.2 on 2025-06-27 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_remove_growthrecord_datetime_growthrecord_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growthrecord',
            name='temperature',
        ),
    ]
